param (
    [Parameter(Mandatory = $true)]
    [string]$NewVersion
)

$today = Get-Date -Format "yyyy-MM-dd"
$root = $PSScriptRoot

Write-Host "Updating Yumna Panel to version $NewVersion..." -ForegroundColor Cyan

# 1. Update Client package.json
$clientPkgPath = "$root\app\client\package.json"
if (Test-Path $clientPkgPath) {
    $clientPkg = Get-Content $clientPkgPath | ConvertFrom-Json
    $clientPkg.version = $NewVersion
    $clientPkg | ConvertTo-Json -Depth 10 | Set-Content $clientPkgPath
    Write-Host "✅ Updated Client package.json" -ForegroundColor Green
}

# 2. Update Server package.json
$serverPkgPath = "$root\app\server\package.json"
if (Test-Path $serverPkgPath) {
    $serverPkg = Get-Content $serverPkgPath | ConvertFrom-Json
    $serverPkg.version = $NewVersion
    $serverPkg | ConvertTo-Json -Depth 10 | Set-Content $serverPkgPath
    Write-Host "✅ Updated Server package.json" -ForegroundColor Green
}

# 3. Update README.md
$readmePath = "$root\README.md"
if (Test-Path $readmePath) {
    $readme = Get-Content $readmePath -Raw
    
    # Update Badge
    $readme = $readme -replace 'badge/version-[\d\.]+-purple', "badge/version-$NewVersion-purple"
    
    # Update Footer Version
    $readme = $readme -replace '\*\*Version\*\*: [\d\.]+', "**Version**: $NewVersion"
    
    # Update Last Updated Date
    $readme = $readme -replace '\*\*Last Updated\*\*: \d{4}-\d{2}-\d{2}', "**Last Updated**: $today"
    
    Set-Content $readmePath -Value $readme -NoNewline
    Write-Host "✅ Updated README.md (Badge, Footer, and Date)" -ForegroundColor Green
}

# 4. Update .env.example files
$envExamples = @("$root\.env.example", "$root\app\server\.env.example")
foreach ($envPath in $envExamples) {
    if (Test-Path $envPath) {
        $envContent = Get-Content $envPath -Raw
        $envContent = $envContent -replace 'PANEL_VERSION=[\d\.]+', "PANEL_VERSION=$NewVersion"
        Set-Content $envPath -Value $envContent -NoNewline
        Write-Host "✅ Updated $envPath" -ForegroundColor Green
    }
}

# 5. Update websites.js (default template)
$websiteJsPath = "$root\app\server\src\routes\hosting\websites.js"
if (Test-Path $websiteJsPath) {
    $webJs = Get-Content $websiteJsPath -Raw
    $webJs = $webJs -replace 'Generated by Yumna Panel v[\d\.]+', "Generated by Yumna Panel v$NewVersion"
    Set-Content $websiteJsPath -Value $webJs -NoNewline
    Write-Host "✅ Updated websites.js template" -ForegroundColor Green
}

Write-Host "`n🚀 Yumna Panel is now at v$NewVersion" -ForegroundColor Yellow
